<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MBuku extends CI_Model
{

    public $table = 'buku';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('judul', $q);
	$this->db->or_like('pengarang', $q);
	$this->db->or_like('penerbit', $q);
	$this->db->or_like('katgori_id', $q);
	$this->db->or_like('kode_buku', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        // Join tabel dengan tabel kategori
        $this->db->select('b.*, k.nama');
        $this->db->from('buku b');
        $this->db->join('kategori k', 'k.id = b.katgori_id');
        //$this->db->join('kategori k', 'k.id = b.katgori_id');

        $this->db->order_by('b.id', $this->order);
        $this->db->like('b.id', $q);
    	$this->db->or_like('b.judul', $q);
    	$this->db->or_like('b.pengarang', $q);
    	$this->db->or_like('b.penerbit', $q);
    	$this->db->or_like('b.kode_buku', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file MBuku.php */
/* Location: ./application/models/MBuku.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-07-21 10:39:39 */
/* http://harviacode.com */